# Generated by Django 6.1 on 2026-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
