# Generated by Django 6.1 on 2026-08-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_medication_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='medication',
            name='days_of_week',
            field=models.CharField(default='', max_length=100),
        ),
    ]
